name: data4all_case_venv
channels:
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11.3
  - pip=23.1.2
  - cudatoolkit=10.2.89
  - cudnn=8.0.4
  - cupti=10.2.89
  - cuda-nvcc=12.1.105
  - keras=2.12.0
  - pip:
    - tensorflow=2.12.0
  - numpy=1.24.3
  - pandas=2.0.1
  - matplotlib=3.7.1
  - seaborn=0.12.2
  - scikit-learn=1.2.2
  - ipykernel=6.22.0
variables:
  TF_CPP_MIN_LOG_LEVEL: 3
  LD_LIBRARY_PATH: /home/matheusmbr/.conda/envs/data4all_case_venv/lib