name: data4all_case_venv
channels:
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - cudatoolkit
  - cudnn
  - cupti
  - cuda-nvcc
  - pip:
    - tensorflow
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - keras
  - ipykernel
variables:
  TF_CPP_MIN_LOG_LEVEL: 3
  LD_LIBRARY_PATH: /home/matheusmbr/.conda/envs/data4all_case_venv/lib